language: rust
sudo: false
matrix:
    include:
        - rust: nightly
branches:
    only:
        - master
script:
    - |
        cargo build --verbose && cargo test --verbose && cargo doc --verbose
